const $=s=>document.querySelector(s);
const statusEl=$('#status'), loginBox=$('#loginBox'), app=$('#app');
function setMsg(text,ok=false){const el=$('#loginMsg');el.textContent=text;el.className='msg '+(ok?'ok':'err')}
async function api(url,opt={}){const headers={...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})};const r=await fetch(url,{credentials:'same-origin',...opt,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'요청에 실패했습니다.');return d}
function preview(){ $('#previewFrame').srcdoc=$('#htmlCode').value }
function resetEditor(){ $('#slug').value='';$('#title').value='';$('#htmlCode').value='<!doctype html>\n<html lang="ko">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>내 사이트</title></head>\n<body><h1>안녕하세요 👋</h1><p>DOYUNGO HOST로 만든 사이트입니다.</p></body>\n</html>';preview();$('#slug').focus() }
async function check(){try{const d=await api('/api/auth');if(d.authenticated){statusEl.textContent='● 관리자 로그인됨';statusEl.style.color='#16834a';loginBox.classList.add('hidden');app.classList.remove('hidden');await loadSites();preview()}else{statusEl.textContent='로그인 필요';statusEl.style.color='#64748b';loginBox.classList.remove('hidden');app.classList.add('hidden')}}catch{statusEl.textContent='연결 오류';statusEl.style.color='#c62b2b'}}
$('#loginBtn').onclick=async()=>{try{await api('/api/auth',{method:'POST',body:JSON.stringify({password:$('#password').value})});setMsg('로그인되었습니다.',true);$('#password').value='';await check()}catch(e){setMsg(e.message)}};
$('#password').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click()});
$('#logoutBtn').onclick=async()=>{await api('/api/auth',{method:'DELETE'});location.reload()};
$('#previewBtn').onclick=preview;$('#refreshPreview').onclick=preview;$('#htmlCode').addEventListener('input',preview);$('#newBtn').onclick=resetEditor;
$('#saveBtn').onclick=async()=>{const slug=$('#slug').value.trim().toLowerCase();if(!/^[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?$/.test(slug)){alert('사이트 주소는 영문 소문자, 숫자, 하이픈으로 1~40자까지 입력하세요.');return}const html=$('#htmlCode').value;if(!html.trim()){alert('HTML 코드를 입력하세요.');return}try{const d=await api('/api/sites',{method:'POST',body:JSON.stringify({slug,html,title:$('#title').value.trim()})});alert('공개 URL이 만들어졌습니다!\n\n'+d.url);await loadSites();window.open(d.url,'_blank','noopener')}catch(e){alert(e.message)}};
async function loadSites(){const box=$('#sitesList');try{const d=await api('/api/sites');box.innerHTML='';if(!d.sites.length){box.innerHTML='<div class="empty">아직 공개한 사이트가 없습니다. 위에서 첫 사이트를 만들어보세요.</div>';return}d.sites.forEach(s=>{const el=document.createElement('div');el.className='site';el.innerHTML=`<div><div class="site-name">${esc(s.slug)}</div><a class="site-url" href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.url)}</a><div class="site-meta">${s.updatedAt?new Date(s.updatedAt).toLocaleString('ko-KR'):''}</div></div><div class="site-actions"><button class="btn-secondary" data-edit="${esc(s.slug)}">편집</button><button class="btn-secondary" data-copy="${esc(s.url)}">URL 복사</button><button class="btn-secondary" data-del="${esc(s.slug)}">삭제</button></div>`;box.appendChild(el)});box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>loadSite(b.dataset.edit));box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='복사됨 ✓';setTimeout(()=>b.textContent='URL 복사',1200)}catch{prompt('URL을 복사하세요',b.dataset.copy)}});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteSite(b.dataset.del))}catch(e){box.innerHTML='<div class="empty">사이트 목록을 불러오지 못했습니다: '+esc(e.message)+'</div>'}}
async function loadSite(slug){try{const d=await api('/api/sites/'+encodeURIComponent(slug));$('#slug').value=d.slug;$('#title').value=d.title||'';$('#htmlCode').value=d.html;preview();document.querySelector('#editor').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){alert(e.message)}}
async function deleteSite(slug){if(!confirm(`/${slug} 사이트를 삭제할까요?`))return;try{await api('/api/sites/'+encodeURIComponent(slug),{method:'DELETE'});await loadSites();resetEditor()}catch(e){alert(e.message)}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#refreshBtn').onclick=loadSites;check();preview();
