const $=s=>document.querySelector(s); const status=$('#status'); const loginBox=$('#loginBox'); const app=$('#app');
function msg(t,ok=false){$('#loginMsg').textContent=t;$('#loginMsg').className='msg '+(ok?'ok':'err')}
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'요청에 실패했습니다.');return d}
async function check(){try{const d=await api('/api/auth');status.textContent=d.authenticated?'관리자 로그인됨':'로그인 필요'; if(d.authenticated){loginBox.classList.add('hidden');app.classList.remove('hidden');loadSites()} }catch{status.textContent='연결 오류'}}
$('#loginBtn').onclick=async()=>{try{await api('/api/auth',{method:'POST',body:JSON.stringify({password:$('#password').value})});msg('로그인되었습니다.',true);await check()}catch(e){msg(e.message)}};
$('#logoutBtn').onclick=async()=>{await api('/api/auth',{method:'DELETE'});location.reload()};
$('#previewBtn').onclick=()=>{$('#preview').srcdoc=$('#htmlCode').value};
$('#saveBtn').onclick=async()=>{const slug=$('#slug').value.trim().toLowerCase();if(!/^[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?$/.test(slug)){alert('사이트 이름은 영문 소문자, 숫자, 하이픈으로 1~40자 입력하세요.');return}try{const d=await api('/api/sites',{method:'POST',body:JSON.stringify({slug,html:$('#htmlCode').value,title:$('#title').value.trim()})});alert('공개 URL이 만들어졌습니다!\n'+d.url);loadSites()}catch(e){alert(e.message)}};
async function loadSites(){try{const d=await api('/api/sites');const box=$('#sites');box.innerHTML='';if(!d.sites.length){box.innerHTML='<p>아직 만든 사이트가 없습니다.</p>';return}d.sites.forEach(s=>{const el=document.createElement('div');el.className='site';el.innerHTML=`<div><b>${esc(s.slug)}</b><br><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.url)}</a></div><div class="actions"><button class="secondary" data-edit="${esc(s.slug)}">불러오기</button><button data-del="${esc(s.slug)}">삭제</button></div>`;box.appendChild(el)});box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>loadSite(b.dataset.edit));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteSite(b.dataset.del))}catch(e){console.error(e)}}
async function loadSite(slug){try{const d=await api('/api/sites/'+encodeURIComponent(slug));$('#slug').value=d.slug;$('#title').value=d.title||'';$('#htmlCode').value=d.html;$('#preview').srcdoc=d.html;window.scrollTo({top:0,behavior:'smooth'})}catch(e){alert(e.message)}}
async function deleteSite(slug){if(!confirm(`/${slug} 사이트를 삭제할까요?`))return;try{await api('/api/sites/'+encodeURIComponent(slug),{method:'DELETE'});loadSites()}catch(e){alert(e.message)}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#refreshBtn').onclick=loadSites;$('#htmlCode').addEventListener('input',()=>{$('#preview').srcdoc=$('#htmlCode').value});check();
